services:
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
      - '8001:8001'
  kafka-to-redis:
    restart: on-failure
    build: ./kafka-to-redis
    environment:
      - INGESTION_EVENTHUB_HOST=pagopa-d-itn-observ-gpd-evh.servicebus.windows.net:9093
      - INGESTION_EVENTHUB_CONN_STRING=${INGESTION_EVENTHUB_CONN_STRING}
      - INGESTION_EVENTHUB_TOPICS=${INGESTION_EVENTHUB_TOPICS}
      - REDIS_PORT=6379
      - REDIS_HOST=redis