const VALID_CF = "PRFGPD24S20B157N";
const INVALID_CF = "invalidCF";
const ENTITY_IDENTIFIER = "PERFORMANCE_TEST_GPD_INGESTION";
const REDIS_ARRAY_IDS_TOKENIZED = "redisTokenized";
const REDIS_ARRAY_IDS_NOT_TOKENIZED = "redisNotTokenized";

module.exports = {
    VALID_CF,
    INVALID_CF,
    ENTITY_IDENTIFIER,
    REDIS_ARRAY_IDS_TOKENIZED,
    REDIS_ARRAY_IDS_NOT_TOKENIZED
}